### PR TITLE
Refactor mongodb_selinux role

### PR DESCRIPTION
**Pull request by cognifloyd**
##### SUMMARY
Each var should come from either vars or defaults, not both.
So, move everything in selinux role to vars/

Then reduce the number of include tasks to one.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
mongodb_selinux role

### CODE REVIEW

**Comment by rhysmeister** [comment]
Looks good although some issues in CI

````
fatal: [ubuntu_16]: FAILED! => {
        "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'os_distribution'\n\nThe error appears to be in '/home/travis/build/ansible-collections/community.mongodb/roles/mongodb_selinux/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# tasks file for mongodb_selinux\n- name: Include OS-specific vars\n  ^ here\n"
    }
````
https://travis-ci.com/github/ansible-collections/community.mongodb/jobs/384369917

**Comment by cognifloyd** [comment]
Fixed the bad var name.
The latest failed test was due to a network error.

**Comment by cognifloyd** [comment]
recheck

**Comment by cognifloyd** [comment]
role tests have all passed in Travis.

**Pull request merged**
