### PR TITLE
Add test workflow

### PR DESCRIPTION
**Pull request by rhysmeister**
##### SUMMARY

Test workflow

### CODE REVIEW

**Comment by cognifloyd** [comment]
Looks like you want `fromJson`
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson

**Comment by rhysmeister** [comment]
> Looks like you want `fromJson`
> https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#fromjson

It's not json (but it might be if I can't figure out another way)

**Comment by cognifloyd** [comment]
This is the post that pointed out `fromJson`:
https://github.community/t/how-to-create-dynamic-matrix-value/17326/3

I'm guessing that JSON is the only way.

**Comment by rhysmeister** [comment]
> This is the post that pointed out `fromJson`:
> https://github.community/t/how-to-create-dynamic-matrix-value/17326/3
> 
> I'm guessing that JSON is the only way.

Doh! This is not the Unix way! There's also a toJson function to perhaps it's as simple as toJson -> fromJson

**Comment by cognifloyd** [comment]
That's looking nice! Then maybe in that preparatory job, we could generate caches for rpm, pip, and galaxy.

**Comment by rhysmeister** [comment]
Pulled across into https://github.com/ansible-collections/community.mongodb/pull/193

**Pull request closed without merging**
