### PR TITLE
Update codecov.sh URL

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/overview/issues/45#issuecomment-829350163

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
@rhysmeister hi, could you please do the same for your other repos if relevant?

**Comment by Andersson007** [comment]
./community.cassandra/tests/coverage.sh
./community.elastic/tests/coverage.sh

**Comment by rhysmeister** [comment]
All done. Sanity tests not relevant here.

**Comment by Andersson007** [comment]
thanks!

**Pull request merged**
