### PR TITLE
Update instructions for running tests

### PR DESCRIPTION
**Pull request by rhysmeister**
##### SUMMARY
Update readme with better ansible-test instructions.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
README.md

##### ADDITIONAL INFORMATION
These instructions should be generic enough to work on MacOS/Linux and Windows (WLSS)

### CODE REVIEW

**Comment by rhysmeister** [comment]
@cognifloyd If you have some time I'd appreciate it if you could test the instructions for running Ansible test here.

**Comment by gwbischof** [comment]
Thanks! These instructions work for me.
I needed one additional command:
`cd mongodb`

**Comment by rhysmeister** [comment]
> Thanks! These instructions work for me.
> I needed one additional command:
> `cd mongodb`

Noted and updated.

**Comment by rhysmeister** [comment]
Confirmed good. Merging.

**Comment by cognifloyd** [comment]
@rhysmeister sorry, I started a new job this past week. So, I'm still figuring out how to arrange things. I'm glad @gwbischof was able to test (thanks!).

**Comment by rhysmeister** [comment]
@cognifloyd   No problem, good luck with the new job.

**Pull request merged**
