### PR TITLE
fix: update horizons on change

### PR DESCRIPTION
**Pull request by tauffredou**
##### SUMMARY

Reconfigure replicaset when `horizons` field changes

`horizons` field is not clearly documented in the MongoDB documentation. It was introduced with [this commit](https://github.com/mongodb/mongo/commit/6784f6568cc45fe25510e2d2393be57daffb5411) and allows to configure multiple names to a replicaset member.

Refs:
- [MongoDB operator documentation ](https://www.mongodb.com/docs/kubernetes-operator/master/reference/k8s-operator-specification/#spec.connectivity.replicaSetHorizons)

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

mongodb_replicaset

##### ADDITIONAL INFORMATION

**before change,** changes are not detected (from integration tests)

```
TASK [mongodb_replicaset : update replica set - horizons] **********************
ok: [testhost]

TASK [mongodb_replicaset : assert] *********************************************
fatal: [testhost]: FAILED! => {
    "assertion": "rs.changed",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

**after change,** changes are detected (from integration tests)

```
TASK [mongodb_replicaset : update replica set - horizons] **********************
changed: [testhost]

TASK [mongodb_replicaset : assert] *********************************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
```

### CODE REVIEW

**Comment by rhysmeister** [comment]
Looks good! Couple of minor things...

- Could you rename the update_horizon.yml file to 638_update_horizons.yml? This is helpful for linking it with this pull.
- There's a couple of quite pedantic sanity checks to correct.

Those aside all looks good. Failing tests in mongodb_user are due to a recent ssl/tls change in MongoDB. We're good to merge.

Cheers,

Rhys

**Comment by tauffredou** [comment]
@rhysmeister hi,

Thanks for the review

- file renamed with f18367a9244130a8547c5ebbc3981e686354d1d3
- linting with pep8 a5288f9be4a4bca96bba5330b7b59cb0dd3b967a

**Comment by tauffredou** [comment]
@rhysmeister many thanks

Thomas

**Comment by rhysmeister** [comment]
@tauffredou Thank you! Released to Galaxy in https://github.com/ansible-collections/community.mongodb/pull/639

**Pull request merged**
