### PR TITLE
community.general.pids -> pids

### PR DESCRIPTION
**Pull request by gwbischof**
##### SUMMARY
I had to make this change to get the integration tests to run.
Maybe I'm missing a setup step or something, but it works when I just use "pids"

### CODE REVIEW

**Comment by rhysmeister** [comment]
What version of Ansible are you using?

**Comment by gwbischof** [comment]
2.9.13

**Comment by cognifloyd** [comment]
Can you copy the error you're seeing when running without this change?

**Comment by gwbischof** [comment]
"""
ansible-test integration --docker default -v --color --python 3.6 mongodb_status
Falling back to tests in "tests/integration/targets/" because "roles/test/" was not found.
Run command: docker images quay.io/ansible/default-test-container:1.10.1 --format '{{json .}}'
Scanning collection root: /Users/gbischof/git/ansible_collections
Including collection: community.mongodb (383 files)
Creating a payload archive containing 6125 files...
Created a 10049397 byte payload archive containing 6125 files in 13 seconds.
Run command: docker run --detach --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged=false --security-opt seccomp=unconfined ...
Run command: docker exec -i 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a dd of=/root/docker.sh bs=65536
Run command: docker exec 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a /bin/bash /root/docker.sh
Run command: docker exec -i 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a dd of=/root/ansible.tgz bs=65536
Run command: docker exec 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a mkdir /root/ansible
Run command: docker exec 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a tar oxzf /root/ansible.tgz -C /root/a ...
Run command: docker exec 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a /usr/bin/env ANSIBLE_TEST_CONTENT_ROO ...
Falling back to tests in "tests/integration/targets/" because "roles/test/" was not found.
Run command: /usr/bin/python3.6 -m pip.__main__ install --disable-pip-version-check -c /root/ansible/test/lib/ansible_test/_dat ...
Ignoring coverage: markers 'python_version > "3.7"' don't match your environment
Ignoring cryptography: markers 'python_version < "2.7"' don't match your environment
Ignoring deepdiff: markers 'python_version < "3"' don't match your environment
Ignoring jinja2: markers 'python_version < "2.7"' don't match your environment
Ignoring urllib3: markers 'python_version < "2.7"' don't match your environment
Ignoring sphinx: markers 'python_version < "2.7"' don't match your environment
Ignoring wheel: markers 'python_version < "2.7"' don't match your environment
Ignoring yamllint: markers 'python_version < "2.7"' don't match your environment
Ignoring paramiko: markers 'python_version < "2.7"' don't match your environment
Ignoring pytest: markers 'python_version < "2.7"' don't match your environment
Ignoring pytest: markers 'python_version == "2.7"' don't match your environment
Ignoring pytest-forked: markers 'python_version < "2.7"' don't match your environment
Ignoring requests: markers 'python_version < "2.7"' don't match your environment
Ignoring virtualenv: markers 'python_version < "2.7"' don't match your environment
Ignoring pathspec: markers 'python_version < "2.7"' don't match your environment
Ignoring pyopenssl: markers 'python_version < "2.7"' don't match your environment
Ignoring pyyaml: markers 'python_version < "2.7"' don't match your environment
Ignoring pycparser: markers 'python_version < "2.7"' don't match your environment
Ignoring xmltodict: markers 'python_version < "2.7"' don't match your environment
Ignoring lxml: markers 'python_version < "2.7"' don't match your environment
Ignoring pyvmomi: markers 'python_version < "2.7"' don't match your environment
Ignoring setuptools: markers 'python_version <= "2.7"' don't match your environment
Ignoring ordereddict: markers 'python_version < "2.7"' don't match your environment
Requirement already satisfied: cryptography in /usr/local/lib/python3.6/dist-packages (from -r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (2.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/dist-packages (from -r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 2)) (2.10.3)
Requirement already satisfied: junit-xml in /usr/local/lib/python3.6/dist-packages (from -r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 3)) (1.8)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from -r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 5)) (5.1.2)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.6/dist-packages (from cryptography->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (1.1.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.6/dist-packages (from cryptography->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (1.13.0)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.6/dist-packages (from cryptography->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (1.12.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 2)) (1.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi!=1.11.3,>=1.8->cryptography->-r /root/ansible/test/lib/ansible_test/_data/requirements/integration.txt (line 1)) (2.19)
Run command: /usr/bin/python3.6 -m pip.__main__ check --disable-pip-version-check
Run command: /usr/bin/python3.6 /root/ansible/test/lib/ansible_test/_data/yamlcheck.py
Running mongodb_status integration test role
Injecting "/tmp/python-s97_uuwo-ansible/python" as a symlink to the "/usr/bin/python3.6" interpreter.
Run command: ansible-playbook mongodb_status-h46qh2bu.yml -i inventory -v
Using /root/ansible/ansible_collections/community/mongodb/tests/output/.tmp/integration/mongodb_status-1zgyw5d1-ÅÑŚÌβŁÈ/tests/integration/integration.cfg as config file
[WARNING]: running playbook inside collection community.mongodb
ERROR! couldn't resolve module/action 'community.general.pids'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/ansible/ansible_collections/community/mongodb/tests/output/.tmp/integration/mongodb_status-1zgyw5d1-ÅÑŚÌβŁÈ/tests/integration/targets/mongodb_status/tasks/main.yml': line 70, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Getting pids for mongod
  ^ here
NOTICE: To resume at this test target, use the option: --start-at mongodb_status
ERROR: Command "ansible-playbook mongodb_status-h46qh2bu.yml -i inventory -v" returned exit status 4.
Run command: docker exec 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a tar czf /root/output.tgz --exclude .t ...
Run command: docker exec -i 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a dd if=/root/output.tgz bs=65536
Run command: tar oxzf /var/folders/s8/97lzdcxn10q6xp91v0n05pv80000gq/T/ansible-result-7jbw7kjm.tgz -C /Users/gbischof/git/ansib ...
Run command: docker rm -f 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a
ERROR: Command "docker exec 0c3ec3c7bac39738afbbb9125e0b5260bda9aea5a2dce601614688db3883397a /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible/ansible_collections/community/mongodb LC_ALL=en_US.UTF-8 /usr/bin/python3.6 /root/ansible/bin/ansible-test integration -v --python 3.6 mongodb_status --metadata metadata-onb5x7il.json --truncate 132 --redact --color yes --requirements --allow-destructive" returned exit status 1.
"""

**Comment by rhysmeister** [comment]
Try Ansible 2.10. 2.9 did/does have support for collections although it was still in development then. They've obviously fixed the namespacing a bit now but the community.general bit was added because earlier versions didn't resolve modules names like it seems to now. I'm mindful to leave it as is because AFAIk it's best practice to fully qualify the module name. In the event some other project adds a module called community.someproject.pids we won't clash.

Cheers,

Rhys

**Comment by gwbischof** [comment]
Same error with ansible 2.10. Also still getting the error after running
`ansible-galaxy collection install community.general`

I'm on OSX and using a conda environment. Could that be the problem?

**Comment by rhysmeister** [comment]
Hello,

RE: conda, not really but it's best to work in a virtualenv for this. I should have this documented really but the following should work. Ansible 2.9 was a bit funny about specific paths if I remember correctly.

First clone the projects...

```
mkdir -p ~/git/ansible_collections/community
cd ~/git/ansible_collections/community
git clone  https://github.com/ansible-collections/community.mongodb.git ./mongodb
git clone  https://github.com/ansible-collections/community.general.git ./general
```

I think community.google and community.kubernetes will get pulled in as dependencies. Then setup a venv...

This section I've just tested on my Mac. Deactivate your conda env with "conda deactivate"

```
cd mongodb
virtualenv venv
source venv/bin/activate
pip install -r requirements-3.6.txt
```

This installs Ansible 2.9. Then we can run the tests...

`ansible-test integration --docker default -v --color --python 3.6 mongodb_status`

You should see something like below indicating it's found the collections...

```
Including collection: community.cassandra (208 files)
Including collection: community.general (3555 files)
Including collection: community.google (626 files)
Including collection: community.kubernetes (76 files)
Including collection: community.mongodb (385 files)
```

Note this is specific for ansible-test 2.9 (possibly later versions too). The normally collection install process should be followed for general ansible use. Let me know how you get on.

Cheers,

Rhys

**Comment by rhysmeister** [comment]
Verified the following works on MacOS 10.15.6...

```bash
mkdir -p ~/git/ansible_collections/community
cd ~/git/ansible_collections/community
git clone  https://github.com/ansible-collections/community.mongodb.git ./mongodb
git clone  https://github.com/ansible-collections/community.general.git ./general
virtualenv venv
source venv/bin/activate
pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check
ansible-test integration --docker default -v --color --python 3.6 mongodb_status
```

N.B. Assumes Docker is already installed.

**Comment by rhysmeister** [comment]
Integrated these instructions into the project readme so closing this. https://github.com/ansible-collections/community.mongodb/pull/205

**Pull request closed without merging**
