### PR TITLE
Drop rhel 8 is_docker checks and make in_docker check more robust (mongodb_linux)

### PR DESCRIPTION
**Pull request by cognifloyd**
I have not been able to reproduce the original issue from #139
So, this removes all the RedHat 8 + docker checks. If we experience issues again, we can bring back some form of docker detection.

I also refactored the docker detection in the `mongodb_linux` role so that it is contained in the role (not spread between role and molecule prepare files). This role needs this more generally (not just in CI) to not set system settings that are not applicable in containers (granted: this is an edge case for most production scenarios).

If we end up needing the docker detection in the other roles, we can probably reuse this refactored docker detection logic in them (maybe by putting it in some kind of utility role).

Discussion in #250

### CODE REVIEW

**Comment by cognifloyd** [comment]
@rhysmeister what do you think of this one? Can I merge it?

**Review by rhysmeister — APPROVED** [review]
@cognifloyd Yep, I think we're good to go.

**Comment by rhysmeister** [comment]
RHEL8 Docker problems...

https://github.com/rhysmeister/AutomatingMongoDBWithAnsible/runs/3053982123?check_suite_focus=true

I might revert for mongodb_mongod unless another solution is possible.

**Comment by cognifloyd** [comment]
I have a couple ideas. I'll submit a PR to your AutomatingMongoDBWithAnsible to see if I can fix it. If not, I'll re-add an is_docker check using `./dockerenv`.

**Comment by cognifloyd** [comment]
See https://github.com/rhysmeister/AutomatingMongoDBWithAnsible/pull/85

**Pull request merged**
