### PR TITLE
x509 membership auth tests

### PR DESCRIPTION
**Pull request by rhysmeister**
##### SUMMARY
Workflow running the tests from tests/ansible-operator (x509 membership auth)

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
x509.yml

### CODE REVIEW

**Comment by rhysmeister** [comment]
Hello @fischerscode, I'm having trouble getting this test environment working again (locally or in the CI). I thought it was an order of operation thing but I can't seem to get it working despite my efforts. Raw log is below but I think the problem is...

`"no matches for kind \"MongoDB\" in version \"mongodb.fischerscode.com/v1alpha1`

This is despite the object exiting..

```
kubectl api-resources | grep -i mongodb
mongodbs                                       mongodb.example.com            true         MongoDB
```

Do you have any idea what I'm doing wrong here?

```
{"level":"info","ts":1604234104.0227413,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
I1101 12:35:04.023410       6 leaderelection.go:242] attempting to acquire leader lease  ansible-operator-system/ansible-operator...
{"level":"info","ts":1604234104.0241601,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I1101 12:35:21.460775       6 leaderelection.go:252] successfully acquired lease ansible-operator-system/ansible-operator
{"level":"info","ts":1604234121.462545,"logger":"controller","msg":"Starting EventSource","controller":"mongodb-controller","source":"kind source: mongodb.fischerscode.com/v1alpha1, Kind=MongoDB"}
{"level":"error","ts":1604234122.127403,"logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"MongoDB.mongodb.fischerscode.com","error":"no matches for kind \"MongoDB\" in version \"mongodb.fischerscode.com/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/source/source.go:117\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:140\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:175\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/manager/internal.go:661"}
{"level":"error","ts":1604234122.1295636,"logger":"cmd","msg":"Proxy or operator exited with error.","Namespace":"","error":"no matches for kind \"MongoDB\" in version \"mongodb.fischerscode.com/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.run\n\tsrc/github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run/cmd.go:223\ngithub.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run.NewCmd.func1\n\tsrc/github.com/operator-framework/operator-sdk/internal/cmd/ansible-operator/run/cmd.go:72\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\nmain.main\n\tsrc/github.com/operator-framework/operator-sdk/cmd/ansible-operator/main.go:34\nruntime.main\n\t/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/runtime/proc.go:203"}
```

**Comment by fischerscode** [comment]
@rhysmeister 
I've created #234 as a Draft. I will use this PR to test my changes to the new test.

(Have you seen [this](https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster)?)

**Comment by rhysmeister** [comment]
Looks like traffic from the localhost VM isn't hitting hte MongoDB instance in the cluster. Perhaps the port-forward isn't correct...

> 2020-11-02T15:57:46.723+0000 I  STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
> 21
> 2020-11-02T15:57:46.723+0000 I  STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
> 22
> 2020-11-02T15:57:46.723+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=2965M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
> 23
> 2020-11-02T15:57:47.414+0000 I  STORAGE  [initandlisten] WiredTiger message [1604332667:414038][7:0x7f8312af6b00], txn-recover: Set global recovery timestamp: (0, 0)
> 24
> 2020-11-02T15:57:47.420+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
> 25
> 2020-11-02T15:57:47.426+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
> 26
> 2020-11-02T15:57:47.429+0000 I  CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
> 27
> 2020-11-02T15:57:47.429+0000 I  CONTROL  [initandlisten] 
> 28
> 2020-11-02T15:57:47.429+0000 I  CONTROL  [initandlisten] 
> 29
> 2020-11-02T15:57:47.429+0000 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
> 30
> 2020-11-02T15:57:47.429+0000 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
> 31
> 2020-11-02T15:57:47.429+0000 I  CONTROL  [initandlisten] 
> 32
> 2020-11-02T15:57:47.429+0000 I  STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: e9a34c3c-c674-4c18-974e-a15bd9a563a9 and options: { uuid: UUID("e9a34c3c-c674-4c18-974e-a15bd9a563a9") }
> 33
> 2020-11-02T15:57:47.435+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns admin.system.version
> 34
> 2020-11-02T15:57:47.435+0000 I  SHARDING [initandlisten] Marking collection admin.system.version as collection version: <unsharded>
> 35
> 2020-11-02T15:57:47.435+0000 I  COMMAND  [initandlisten] setting featureCompatibilityVersion to 4.2
> 36
> 2020-11-02T15:57:47.435+0000 I  SHARDING [initandlisten] Marking collection local.system.replset as collection version: <unsharded>
> 37
> 2020-11-02T15:57:47.435+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
> 38
> 2020-11-02T15:57:47.435+0000 I  SHARDING [initandlisten] Marking collection admin.system.roles as collection version: <unsharded>
> 39
> 2020-11-02T15:57:47.436+0000 I  STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: 3f415ca8-65e3-4732-94b0-1f617a6446db and options: { capped: true, size: 10485760 }
> 40
> 2020-11-02T15:57:47.440+0000 I  INDEX    [initandlisten] index build: done building index _id_ on ns local.startup_log
> 41
> 2020-11-02T15:57:47.440+0000 I  SHARDING [initandlisten] Marking collection local.startup_log as collection version: <unsharded>
> 42
> 2020-11-02T15:57:47.440+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
> 43
> 2020-11-02T15:57:47.444+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
> 44
> 2020-11-02T15:57:47.445+0000 I  CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
> 45
> 2020-11-02T15:57:47.445+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
> 46
> 2020-11-02T15:57:47.445+0000 I  NETWORK  [listener] Listening on 0.0.0.0
> 47
> 2020-11-02T15:57:47.445+0000 I  NETWORK  [listener] waiting for connections on port 27017 ssl
> 48
> 2020-11-02T15:57:47.445+0000 I  STORAGE  [LogicalSessionCacheRefresh] createCollection: config.system.sessions with provided UUID: e58016c1-669f-459d-98e7-1891c239a3e2 and options: { uuid: UUID("e58016c1-669f-459d-98e7-1891c239a3e2") }
> 49
> 2020-11-02T15:57:47.451+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index _id_ on ns config.system.sessions
> 50
> 2020-11-02T15:57:47.456+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: starting on config.system.sessions properties: { v: 2, key: { lastUse: 1 }, name: "lsidTTLIndex", ns: "config.system.sessions", expireAfterSeconds: 1800 } using method: Hybrid
> 51
> 2020-11-02T15:57:47.456+0000 I  INDEX    [LogicalSessionCacheRefresh] build may temporarily use up to 200 megabytes of RAM
> 52
> 2020-11-02T15:57:47.456+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: collection scan done. scanned 0 total records in 0 seconds
> 53
> 2020-11-02T15:57:47.456+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: inserted 0 keys from external sorter into index in 0 seconds
> 54
> 2020-11-02T15:57:47.457+0000 I  INDEX    [LogicalSessionCacheRefresh] index build: done building index lsidTTLIndex on ns config.system.sessions
> 55
> 2020-11-02T15:57:48.000+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>
> 56
> 2020-11-02T15:57:56.732+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:47902 #1 (1 connection now open)
> 57
> 2020-11-02T15:57:56.732+0000 I  NETWORK  [conn1] end connection 172.17.0.1:47902 (0 connections now open)
> 58
> 2020-11-02T15:58:03.176+0000 I  NETWORK  [listener] connection accepted from 172.17.0.6:58124 #2 (1 connection now open)
> 59
> 2020-11-02T15:58:03.187+0000 W  NETWORK  [conn2] Client connecting with server's own TLS certificate
> 60
> 2020-11-02T15:58:03.187+0000 I  NETWORK  [conn2] received client metadata from 172.17.0.6:58124 conn2: { driver: { name: "PyMongo", version: "3.11.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.4.0-1031-azure" }, platform: "CPython 3.6.8.final.0" }
> 61
> 2020-11-02T15:58:03.189+0000 I  NETWORK  [listener] connection accepted from 172.17.0.6:58126 #3 (2 connections now open)
> 62
> 2020-11-02T15:58:03.195+0000 W  NETWORK  [conn3] Client connecting with server's own TLS certificate
> 63
> 2020-11-02T15:58:03.196+0000 I  NETWORK  [conn3] received client metadata from 172.17.0.6:58126 conn3: { driver: { name: "PyMongo", version: "3.11.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.4.0-1031-azure" }, platform: "CPython 3.6.8.final.0" }
> 64
> 2020-11-02T15:58:03.196+0000 I  ACCESS   [conn3]  authenticate db: $external { authenticate: 1, mechanism: "MONGODB-X509", $db: "$external", $readPreference: { mode: "primary" } }
> 65
> 2020-11-02T15:58:03.196+0000 W  ACCESS   [conn3] Client isn't a mongod or mongos, but is connecting with a certificate with cluster membership
> 66
> 2020-11-02T15:58:03.196+0000 I  ACCESS   [conn3] Successfully authenticated as principal CN=mongodb-sample.default.svc.cluster.local,OU=organizationUnit,O=organizationName on $external from client 172.17.0.6:58126
> 67
> 2020-11-02T15:58:03.197+0000 I  SHARDING [conn3] Marking collection admin.system.users as collection version: <unsharded>
> 68
> 2020-11-02T15:58:03.237+0000 I  STORAGE  [conn3] createCollection: admin.system.users with generated UUID: 0870a847-ea65-44b4-9666-3e99bd824c7a and options: {}
> 69
> 2020-11-02T15:58:03.242+0000 I  INDEX    [conn3] index build: done building index _id_ on ns admin.system.users
> 70
> 2020-11-02T15:58:03.245+0000 I  INDEX    [conn3] index build: done building index user_1_db_1 on ns admin.system.users
> 71
> 2020-11-02T15:58:03.246+0000 I  NETWORK  [conn2] end connection 172.17.0.6:58124 (1 connection now open)
> 72
> 2020-11-02T15:58:03.246+0000 I  NETWORK  [conn3] end connection 172.17.0.6:58126 (0 connections now open)
> 73
> 2020-11-02T15:58:06.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:47990 #4 (1 connection now open)
> 74
> 2020-11-02T15:58:06.732+0000 I  NETWORK  [conn4] end connection 172.17.0.1:47990 (0 connections now open)
> 75
> 2020-11-02T15:58:14.987+0000 I  NETWORK  [listener] connection accepted from 172.17.0.6:58234 #5 (1 connection now open)
> 76
> 2020-11-02T15:58:14.993+0000 W  NETWORK  [conn5] Client connecting with server's own TLS certificate
> 77
> 2020-11-02T15:58:14.993+0000 I  NETWORK  [conn5] received client metadata from 172.17.0.6:58234 conn5: { driver: { name: "PyMongo", version: "3.11.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.4.0-1031-azure" }, platform: "CPython 3.6.8.final.0" }
> 78
> 2020-11-02T15:58:14.995+0000 I  NETWORK  [listener] connection accepted from 172.17.0.6:58236 #6 (2 connections now open)
> 79
> 2020-11-02T15:58:15.001+0000 W  NETWORK  [conn6] Client connecting with server's own TLS certificate
> 80
> 2020-11-02T15:58:15.002+0000 I  NETWORK  [conn6] received client metadata from 172.17.0.6:58236 conn6: { driver: { name: "PyMongo", version: "3.11.0" }, os: { type: "Linux", name: "Linux", architecture: "x86_64", version: "5.4.0-1031-azure" }, platform: "CPython 3.6.8.final.0" }
> 81
> 2020-11-02T15:58:15.002+0000 I  ACCESS   [conn6]  authenticate db: $external { authenticate: 1, mechanism: "MONGODB-X509", $db: "$external", $readPreference: { mode: "primary" } }
> 82
> 2020-11-02T15:58:15.002+0000 W  ACCESS   [conn6] Client isn't a mongod or mongos, but is connecting with a certificate with cluster membership
> 83
> 2020-11-02T15:58:15.002+0000 I  ACCESS   [conn6] Successfully authenticated as principal CN=mongodb-sample.default.svc.cluster.local,OU=organizationUnit,O=organizationName on $external from client 172.17.0.6:58236
> 84
> 2020-11-02T15:58:15.044+0000 I  NETWORK  [conn5] end connection 172.17.0.6:58234 (1 connection now open)
> 85
> 2020-11-02T15:58:15.044+0000 I  NETWORK  [conn6] end connection 172.17.0.6:58236 (0 connections now open)
> 86
> 2020-11-02T15:58:16.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48088 #7 (1 connection now open)
> 87
> 2020-11-02T15:58:16.732+0000 I  NETWORK  [conn7] end connection 172.17.0.1:48088 (0 connections now open)
> 88
> 2020-11-02T15:58:20.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48114 #8 (1 connection now open)
> 89
> 2020-11-02T15:58:20.514+0000 I  NETWORK  [conn8] end connection 172.17.0.1:48114 (0 connections now open)
> 90
> 2020-11-02T15:58:26.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48176 #9 (1 connection now open)
> 91
> 2020-11-02T15:58:26.732+0000 I  NETWORK  [conn9] end connection 172.17.0.1:48176 (0 connections now open)
> 92
> 2020-11-02T15:58:30.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48194 #10 (1 connection now open)
> 93
> 2020-11-02T15:58:30.514+0000 I  NETWORK  [conn10] end connection 172.17.0.1:48194 (0 connections now open)
> 94
> 2020-11-02T15:58:31.428+0000 I  NETWORK  [listener] connection accepted from 172.17.0.6:58394 #11 (1 connection now open)
> 95
> 2020-11-02T15:58:31.433+0000 W  NETWORK  [conn11] Client connecting with server's own TLS certificate
> 96
> 2020-11-02T15:58:31.434+0000 I  NETWORK  [conn11] received client metadata from 172.17.0.6:58394 conn11: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "4.2.10" }, os: { type: "Linux", name: "Red Hat Enterprise Linux release 8.2 (Ootpa)", architecture: "x86_64", version: "Kernel 5.4.0-1031-azure" } }
> 97
> 2020-11-02T15:58:31.434+0000 I  ACCESS   [conn11]  authenticate db: $external { authenticate: 1, mechanism: "MONGODB-X509", user: "CN=mongodb-sample.default.svc.cluster.local,OU=organizationUnit,O=organizationName", $db: "$external" }
> 98
> 2020-11-02T15:58:31.434+0000 W  ACCESS   [conn11] Client isn't a mongod or mongos, but is connecting with a certificate with cluster membership
> 99
> 2020-11-02T15:58:31.434+0000 I  ACCESS   [conn11] Successfully authenticated as principal CN=mongodb-sample.default.svc.cluster.local,OU=organizationUnit,O=organizationName on $external from client 172.17.0.6:58394
> 101
> 2020-11-02T15:58:31.441+0000 I  NETWORK  [conn11] end connection 172.17.0.6:58394 (0 connections now open)
> 102
> 2020-11-02T15:58:36.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48280 #12 (1 connection now open)
> 103
> 2020-11-02T15:58:36.732+0000 I  NETWORK  [conn12] end connection 172.17.0.1:48280 (0 connections now open)
> 104
> 2020-11-02T15:58:40.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48306 #13 (1 connection now open)
> 105
> 2020-11-02T15:58:40.514+0000 I  NETWORK  [conn13] end connection 172.17.0.1:48306 (0 connections now open)
> 106
> 2020-11-02T15:58:46.734+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48360 #14 (1 connection now open)
> 107
> 2020-11-02T15:58:46.734+0000 I  NETWORK  [conn14] end connection 172.17.0.1:48360 (0 connections now open)
> 108
> 2020-11-02T15:58:50.514+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48386 #15 (1 connection now open)
> 109
> 2020-11-02T15:58:50.514+0000 I  NETWORK  [conn15] end connection 172.17.0.1:48386 (0 connections now open)
> 110
> 2020-11-02T15:58:56.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48448 #16 (1 connection now open)
> 111
> 2020-11-02T15:58:56.732+0000 I  NETWORK  [conn16] end connection 172.17.0.1:48448 (0 connections now open)
> 112
> 2020-11-02T15:59:00.514+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48466 #17 (1 connection now open)
> 113
> 2020-11-02T15:59:00.515+0000 I  NETWORK  [conn17] end connection 172.17.0.1:48466 (0 connections now open)
> 114
> 2020-11-02T15:59:06.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48518 #18 (1 connection now open)
> 115
> 2020-11-02T15:59:06.732+0000 I  NETWORK  [conn18] end connection 172.17.0.1:48518 (0 connections now open)
> 116
> 2020-11-02T15:59:10.514+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48546 #19 (1 connection now open)
> 117
> 2020-11-02T15:59:10.514+0000 I  NETWORK  [conn19] end connection 172.17.0.1:48546 (0 connections now open)
> 118
> 2020-11-02T15:59:16.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48598 #20 (1 connection now open)
> 119
> 2020-11-02T15:59:16.732+0000 I  NETWORK  [conn20] end connection 172.17.0.1:48598 (0 connections now open)
> 120
> 2020-11-02T15:59:20.514+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48626 #21 (1 connection now open)
> 121
> 2020-11-02T15:59:20.516+0000 I  NETWORK  [conn21] end connection 172.17.0.1:48626 (0 connections now open)
> 122
> 2020-11-02T15:59:26.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48678 #22 (1 connection now open)
> 123
> 2020-11-02T15:59:26.732+0000 I  NETWORK  [conn22] end connection 172.17.0.1:48678 (0 connections now open)
> 124
> 2020-11-02T15:59:30.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48696 #23 (1 connection now open)
> 125
> 2020-11-02T15:59:30.514+0000 I  NETWORK  [conn23] end connection 172.17.0.1:48696 (0 connections now open)
> 126
> 2020-11-02T15:59:36.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48748 #24 (1 connection now open)
> 127
> 2020-11-02T15:59:36.734+0000 I  NETWORK  [conn24] end connection 172.17.0.1:48748 (0 connections now open)
> 128
> 2020-11-02T15:59:40.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48774 #25 (1 connection now open)
> 129
> 2020-11-02T15:59:40.514+0000 I  NETWORK  [conn25] end connection 172.17.0.1:48774 (0 connections now open)
> 130
> 2020-11-02T15:59:46.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48826 #26 (1 connection now open)
> 131
> 2020-11-02T15:59:46.732+0000 I  NETWORK  [conn26] end connection 172.17.0.1:48826 (0 connections now open)
> 132
> 2020-11-02T15:59:50.514+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48854 #27 (1 connection now open)
> 133
> 2020-11-02T15:59:50.514+0000 I  NETWORK  [conn27] end connection 172.17.0.1:48854 (0 connections now open)
> 134
> 2020-11-02T15:59:56.732+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48916 #28 (1 connection now open)
> 135
> 2020-11-02T15:59:56.732+0000 I  NETWORK  [conn28] end connection 172.17.0.1:48916 (0 connections now open)
> 136
> 2020-11-02T16:00:00.514+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48934 #29 (1 connection now open)
> 137
> 2020-11-02T16:00:00.514+0000 I  NETWORK  [conn29] end connection 172.17.0.1:48934 (0 connections now open)
> 138
> 2020-11-02T16:00:06.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:48986 #30 (1 connection now open)
> 139
> 2020-11-02T16:00:06.732+0000 I  NETWORK  [conn30] end connection 172.17.0.1:48986 (0 connections now open)
> 140
> 2020-11-02T16:00:10.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49014 #31 (1 connection now open)
> 141
> 2020-11-02T16:00:10.514+0000 I  NETWORK  [conn31] end connection 172.17.0.1:49014 (0 connections now open)
> 142
> 2020-11-02T16:00:16.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49066 #32 (1 connection now open)
> 143
> 2020-11-02T16:00:16.732+0000 I  NETWORK  [conn32] end connection 172.17.0.1:49066 (0 connections now open)
> 144
> 2020-11-02T16:00:20.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49084 #33 (1 connection now open)
> 145
> 2020-11-02T16:00:20.516+0000 I  NETWORK  [conn33] end connection 172.17.0.1:49084 (0 connections now open)
> 146
> 2020-11-02T16:00:26.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49138 #34 (1 connection now open)
> 147
> 2020-11-02T16:00:26.731+0000 I  NETWORK  [conn34] end connection 172.17.0.1:49138 (0 connections now open)
> 148
> 2020-11-02T16:00:30.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49164 #35 (1 connection now open)
> 149
> 2020-11-02T16:00:30.514+0000 I  NETWORK  [conn35] end connection 172.17.0.1:49164 (0 connections now open)
> 150
> 2020-11-02T16:00:36.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49216 #36 (1 connection now open)
> 151
> 2020-11-02T16:00:36.735+0000 I  NETWORK  [conn36] end connection 172.17.0.1:49216 (0 connections now open)
> 152
> 2020-11-02T16:00:40.514+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49242 #37 (1 connection now open)
> 153
> 2020-11-02T16:00:40.514+0000 I  NETWORK  [conn37] end connection 172.17.0.1:49242 (0 connections now open)
> 154
> 2020-11-02T16:00:46.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49294 #38 (1 connection now open)
> 155
> 2020-11-02T16:00:46.732+0000 I  NETWORK  [conn38] end connection 172.17.0.1:49294 (0 connections now open)
> 156
> 2020-11-02T16:00:50.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49312 #39 (1 connection now open)
> 157
> 2020-11-02T16:00:50.514+0000 I  NETWORK  [conn39] end connection 172.17.0.1:49312 (0 connections now open)
> 158
> 2020-11-02T16:00:56.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49374 #40 (1 connection now open)
> 159
> 2020-11-02T16:00:56.732+0000 I  NETWORK  [conn40] end connection 172.17.0.1:49374 (0 connections now open)
> 160
> 2020-11-02T16:01:00.515+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49400 #41 (1 connection now open)
> 161
> 2020-11-02T16:01:00.515+0000 I  NETWORK  [conn41] end connection 172.17.0.1:49400 (0 connections now open)
> 162
> 2020-11-02T16:01:06.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49454 #42 (1 connection now open)
> 163
> 2020-11-02T16:01:06.732+0000 I  NETWORK  [conn42] end connection 172.17.0.1:49454 (0 connections now open)
> 164
> 2020-11-02T16:01:10.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49482 #43 (1 connection now open)
> 165
> 2020-11-02T16:01:10.514+0000 I  NETWORK  [conn43] end connection 172.17.0.1:49482 (0 connections now open)
> 166
> 2020-11-02T16:01:16.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49534 #44 (1 connection now open)
> 167
> 2020-11-02T16:01:16.732+0000 I  NETWORK  [conn44] end connection 172.17.0.1:49534 (0 connections now open)
> 168
> 2020-11-02T16:01:20.514+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49552 #45 (1 connection now open)
> 169
> 2020-11-02T16:01:20.514+0000 I  NETWORK  [conn45] end connection 172.17.0.1:49552 (0 connections now open)
> 170
> 2020-11-02T16:01:26.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49604 #46 (1 connection now open)
> 171
> 2020-11-02T16:01:26.732+0000 I  NETWORK  [conn46] end connection 172.17.0.1:49604 (0 connections now open)
> 172
> 2020-11-02T16:01:30.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49630 #47 (1 connection now open)
> 173
> 2020-11-02T16:01:30.515+0000 I  NETWORK  [conn47] end connection 172.17.0.1:49630 (0 connections now open)
> 174
> 2020-11-02T16:01:36.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49684 #48 (1 connection now open)
> 175
> 2020-11-02T16:01:36.732+0000 I  NETWORK  [conn48] end connection 172.17.0.1:49684 (0 connections now open)
> 176
> 2020-11-02T16:01:40.514+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49710 #49 (1 connection now open)
> 177
> 2020-11-02T16:01:40.514+0000 I  NETWORK  [conn49] end connection 172.17.0.1:49710 (0 connections now open)
> 178
> 2020-11-02T16:01:46.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49762 #50 (1 connection now open)
> 179
> 2020-11-02T16:01:46.732+0000 I  NETWORK  [conn50] end connection 172.17.0.1:49762 (0 connections now open)
> 180
> 2020-11-02T16:01:50.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49780 #51 (1 connection now open)
> 181
> 2020-11-02T16:01:50.514+0000 I  NETWORK  [conn51] end connection 172.17.0.1:49780 (0 connections now open)
> 182
> 2020-11-02T16:01:56.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49842 #52 (1 connection now open)
> 183
> 2020-11-02T16:01:56.732+0000 I  NETWORK  [conn52] end connection 172.17.0.1:49842 (0 connections now open)
> 184
> 2020-11-02T16:02:00.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49868 #53 (1 connection now open)
> 185
> 2020-11-02T16:02:00.515+0000 I  NETWORK  [conn53] end connection 172.17.0.1:49868 (0 connections now open)
> 186
> 2020-11-02T16:02:06.731+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49920 #54 (1 connection now open)
> 187
> 2020-11-02T16:02:06.733+0000 I  NETWORK  [conn54] end connection 172.17.0.1:49920 (0 connections now open)
> 188
> 2020-11-02T16:02:10.513+0000 I  NETWORK  [listener] connection accepted from 172.17.0.1:49948 #55 (1 connection now open)
> 189
>

**Comment by fischerscode** [comment]
@rhysmeister 
> Looks like traffic from the localhost VM isn't hitting the MongoDB instance in the cluster. Perhaps the port-forward isn't correct...

I had this problem, too. It seems like `kubectl port-forward` requires socat.
```yaml
      - name: Install socat
        run: |
          sudo apt update
          sudo apt install socat
```

**Comment by rhysmeister** [comment]
> @rhysmeister
> 
> > Looks like traffic from the localhost VM isn't hitting the MongoDB instance in the cluster. Perhaps the port-forward isn't correct...
> 
> I had this problem, too. It seems like `kubectl port-forward` requires socat.
> 
> ```yaml
>       - name: Install socat
>         run: |
>           sudo apt update
>           sudo apt install socat
> ```

That was it. Thanks again!

R

**Comment by rhysmeister** [comment]
@fischerscode OK. I think I'm done here. I'm testing with three modules but all the pymongo based modules should work with x509 membership auth the connection code is mostly shared. I guess the use case for membership auth is probably not relevant for all modules. Thanks again for the help in getting this working.

**Comment by fischerscode** [comment]
To be honest, I am not too familiar with all the modules.
In my opinion, testing only three modules is sufficient, as, from my understanding,  all modules share the same code for x509 membership auth.

**Pull request merged**
